name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_FRONTEND: gamezone-frontend
  ECR_REPOSITORY_BACKEND: gamezone-backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install
    
    - name: Build Docker Images
      run: |
        docker build -t gamezone-frontend:test ./frontend
        docker build -t gamezone-backend:test ./backend
    
    - name: Run Tests
      run: echo "Tests would run here"
  
  terraform-plan:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -var="key_name=${{ secrets.AWS_KEY_NAME }}"
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0
        terraform_wrapper: false
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
    
    - name: Import Existing ECR Repositories
      working-directory: ./terraform
      run: |
        terraform import aws_ecr_repository.frontend gamezone-frontend || true
        terraform import aws_ecr_repository.backend gamezone-backend || true
      continue-on-error: true
    
    - name: Terraform Apply (Create infrastructure)
      working-directory: ./terraform
      run: terraform apply -auto-approve -var="key_name=${{ secrets.AWS_KEY_NAME }}"
    
    - name: Get ECR Repository URLs
      id: ecr-urls
      working-directory: ./terraform
      run: |
        echo "frontend_repo=$(terraform output -raw ecr_frontend_repository_url)" >> $GITHUB_OUTPUT
        echo "backend_repo=$(terraform output -raw ecr_backend_repository_url)" >> $GITHUB_OUTPUT
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and Push Frontend Image
      env:
        ECR_REPO: ${{ steps.ecr-urls.outputs.frontend_repo }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REPO:$IMAGE_TAG ./frontend
        docker push $ECR_REPO:$IMAGE_TAG
        docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
        docker push $ECR_REPO:latest
    
    - name: Build and Push Backend Image
      env:
        ECR_REPO: ${{ steps.ecr-urls.outputs.backend_repo }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REPO:$IMAGE_TAG ./backend
        docker push $ECR_REPO:$IMAGE_TAG
        docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
        docker push $ECR_REPO:latest
    
    - name: Update EC2 Instance (Redeploy)
      run: |
        INSTANCE_IP=$(cd terraform && terraform output -raw instance_public_ip)
        echo "Application deployed at: http://$INSTANCE_IP"
